#!/bin/bash

architecture="$(uname -p)"

if [ $architecture = "x86_64" ] ; then
  export QML2_IMPORT_PATH=`pwd`/usr/lib/x86_64-linux-gnu/qt5/qml #desktop
elif [ $architecture = "aarch64" ] ; then
  export QML2_IMPORT_PATH=`pwd`/usr/lib/aarch64-linux-gnu/qt5/qml # phone (arm64)
else
  export QML2_IMPORT_PATH=`pwd`/usr/lib/arm-linux-gnueabihf/qt5/qml/ #phone (armhf)
fi

telescope $@
