#!/bin/bash

architecture="$(uname -p)"

if [ $architecture = "x86_64" ] ; then
  export QML2_IMPORT_PATH=`pwd`/usr/lib/x86_64-linux-gnu/qt5/qml #desktop
else
  export QML2_IMPORT_PATH=`pwd`/usr/lib/arm-linux-gnueabihf/qt5/qml/ #phone
fi

telescope $@
